apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: nexus-backend
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    spec:
      containers:
        - image: gcr.io/PROJECT_ID/nexus-backend:latest
          ports:
            - containerPort: 3001
          env:
            - name: NODE_ENV
              value: production
            - name: PORT
              value: "3001"
      containerConcurrency: 80
      timeoutSeconds: 300


