apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: nexus-frontend
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    spec:
      containers:
        - image: gcr.io/PROJECT_ID/nexus-frontend:latest
          ports:
            - containerPort: 8080
          env:
            - name: NODE_ENV
              value: production
      containerConcurrency: 80
      timeoutSeconds: 300


